services:
  - type: web
    name: anant-sutram-api
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    rootDir: server
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: "*" # Allow any frontend during setup, can be tightened later
      - key: GOOGLE_CLIENT_ID
        value: 1051430268469-tjugvgi93nmpvl3beo6fsibt9qvgm5k4.apps.googleusercontent.com
