/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── CSS-var driven tokens ──────────────────────────────────────
        bg:       'var(--bg-app)',
        surface:  'var(--bg-surface)',
        surface2: 'var(--bg-elevated)',
        surface3: 'var(--bg-card)',
        nav:      'var(--bg-nav)',
        primary:   'var(--color-primary)',
        'primary-light': 'var(--color-primary-light)',
        secondary: 'var(--color-secondary)',
        teal:      'var(--color-teal)',
        success: 'var(--color-success)',
        alert:   'var(--color-alert)',
        gold:    'var(--color-gold)',
        main:      'var(--text-main)',
        sub:       'var(--text-sub)',
        muted:     'var(--text-muted)',
        subtle:    'var(--border-subtle)',
        soft:      'var(--border-soft)',
        // ── Pastel palette ────────────────────────────────────────────
        'pastel-purple':  'var(--pastel-purple)',
        'pastel-purple2': 'var(--pastel-purple-2)',
        'pastel-green':   'var(--pastel-green)',
        'pastel-green2':  'var(--pastel-green-2)',
        'pastel-pink':    'var(--pastel-pink)',
        'pastel-pink2':   'var(--pastel-pink-2)',
        // ── Static accents ────────────────────────────────────────────
        amber:   '#FFA94D',
        rose:    '#FF6B6B',
      },
      fontFamily: {
        body:    ['Nunito', 'Inter', '-apple-system', 'BlinkMacSystemFont', '"SF Pro Rounded"', '"SF Pro Display"', '"Segoe UI"', 'sans-serif'],
        display: ['Nunito', 'Inter', '-apple-system', 'BlinkMacSystemFont', '"SF Pro Rounded"', '"SF Pro Display"', '"Segoe UI"', 'sans-serif'],
        mono:    ['JetBrains Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        'xs':   ['12px', { lineHeight: '16px', letterSpacing: '0.03em' }],
        'sm':   ['14px', { lineHeight: '20px', letterSpacing: '0.01em' }],
        'base': ['16px', { lineHeight: '24px' }],
        'md':   ['17px', { lineHeight: '24px' }],
        'lg':   ['20px', { lineHeight: '28px' }],
        'xl':   ['24px', { lineHeight: '32px' }],
        '2xl':  ['28px', { lineHeight: '36px' }],
        '3xl':  ['32px', { lineHeight: '40px' }],
        '4xl':  ['40px', { lineHeight: '48px' }],
      },
      borderRadius: {
        'xs':   '6px',
        'sm':   '10px',
        'md':   '14px',
        'lg':   '18px',
        'xl':   '22px',
        '2xl':  '16px',
        '3xl':  '24px',
        '4xl':  '32px',
        'card': '20px',
        'tile': '22px',
        'pill': '100px',
      },
      animation: {
        'float':       'float 4s ease-in-out infinite',
        'pulse-glow':  'pulse-glow 3s ease-in-out infinite',
        'shimmer':     'shimmer 1.8s linear infinite',
        'slide-up':    'slide-up 0.4s cubic-bezier(0.16,1,0.3,1) forwards',
        'fade-in':     'fade-in 0.3s ease-out forwards',
        'breath':      'breath-expand 4s ease-in-out infinite',
        'spin-slow':   'spin 3s linear infinite',
        'pop-in':      'pop-in 0.4s cubic-bezier(0.34,1.56,0.64,1) forwards',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':       { transform: 'translateY(-8px)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(92,124,250,0.12)' },
          '50%':       { boxShadow: '0 0 40px rgba(92,124,250,0.30)' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'slide-up': {
          from: { transform: 'translateY(20px)', opacity: '0' },
          to:   { transform: 'translateY(0)',    opacity: '1' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        'breath-expand': {
          '0%, 100%': { transform: 'scale(1)',    opacity: '0.6' },
          '50%':       { transform: 'scale(1.15)', opacity: '1' },
        },
        'pop-in': {
          '0%':   { transform: 'scale(0.85)', opacity: '0' },
          '70%':  { transform: 'scale(1.06)', opacity: '1' },
          '100%': { transform: 'scale(1)' },
        },
      },
      backdropBlur: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        xl: '20px',
        '2xl': '32px',
        '3xl': '48px',
      },
      boxShadow: {
        'card':         '0 2px 16px rgba(0,0,0,0.06), 0 1px 4px rgba(0,0,0,0.04)',
        'card-hover':   '0 8px 32px rgba(0,0,0,0.10), 0 2px 8px rgba(0,0,0,0.06)',
        'card-dark':    '0 8px 32px rgba(0,0,0,0.4)',
        'tile':         '0 3px 14px rgba(0,0,0,0.07)',
        'glow-primary': '0 0 24px rgba(92,124,250,0.20)',
        'glow-teal':    '0 0 20px rgba(56,217,169,0.16)',
        'glow-gold':    '0 0 20px rgba(255,169,77,0.18)',
        'btn':          '0 4px 16px rgba(92,124,250,0.3)',
        'btn-hover':    '0 6px 24px rgba(92,124,250,0.45)',
        'nav':          '0 -2px 20px rgba(0,0,0,0.06)',
        'premium':      '0 4px 20px rgba(0,0,0,0.06)',
      },
      spacing: {
        'safe': 'max(env(safe-area-inset-top), 16px)',
      },
    },
  },
  plugins: [],
}
